AWSTemplateFormatVersion: '2010-09-09'
Description: Jenkins Server on EC2 Instance with EBS Volume.

Parameters:
  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
    Description: EC2 instance type for the Jenkins server
  RootVolumeSize:
    Type: Number
    Default: 30
    Description: Size of the EBS volume (in GB) for Jenkins data
  AmiID:
    Type: String
    Default: ami-02d7fd1c2af6eead0
    Description: Specify AMI Id (check your region first)
  Tag: 
    Type: String
    Description: Specify tag to be used as prefix for resources tags.
    Default: Test

Resources:
  NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Sub ${Tag}-${AWS::Region}-JenkinsKeyPair
  JenkinsServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${Tag}-${AWS::Region}-JenkinsSecurityGroup


  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiID # Amazon Linux 2
      InstanceType: !Ref InstanceType
      KeyName: !Ref NewKeyPair # Replace with your EC2 key pair name
      SecurityGroupIds:
        - !Ref JenkinsServerSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: !Ref RootVolumeSize
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
            # Import key from Jenkins
            sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
            # Install Java-11
            amazon-linux-extras install java-openjdk11 -y
            # Install Jenkins
            yum install jenkins -y

            # You can enable the Jenkins service to start at boot with the command:
            systemctl enable jenkins
            # You can start the Jenkins service with the command:
            systemctl start jenkins
            # You can check the status of the Jenkins service using the command:
            systemctl status jenkins
      Tags:
        - Key: Name
          Value: !Sub ${Tag}-${AWS::Region}-JenkinsServer
Outputs:
  JenkinsURL:
    Description: Jenkins URL
    Value: !Sub http://${JenkinsInstance.PublicDnsName}:8080
