AWSTemplateFormatVersion: '2010-09-09'
Description: Customer Managed AWS KMS Template
Parameters:
  KeyAdminUserName:
    Type: String
    Description: Specify Username of the IAM user who should have administrative permissions on the KMS key. 
    Default: awskb
    AllowedValues:
      - test
      - awskb
      - test2
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: Test
  Region:
    Type: String
    Default: us-west-2
    AllowedValues: [ap-northeast-1,ap-northeast-2,ap-south-1,ap-southeast-1,ap-southeast-2,ca-central-1,eu-central-1,eu-north-1,eu-south-1,eu-west-1,eu-west-2,eu-west-3,sa-east-1,us-east-1,us-east-2,us-west-1,us-west-2]
    Description: Select the region for deployment
Resources:
  CustomerManagedKey:
    Type: AWS::KMS::Key
    Properties:
      Description: My Customer Managed KMS Key
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: '*'
          - Sid: Allow Key Administrators to manage key
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/${KeyAdminUserName}"
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:TagResource
              - kms:UntagResource
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${Region}-CMK

  CMKAlias:
    Type: AWS::KMS::Alias
    Properties:
      # AliasName: alias/cloudtrail
      AliasName: !Join ["",["alias/", !Ref EnvironmentName,"-", !Ref Region,"-", "cmk"]]
      TargetKeyId: !Ref CustomerManagedKey

Outputs:
  CustomerManagedKeyValue:
    Description: Customer Manager Key Details
    Value: !Ref CustomerManagedKey